(IMMEDIATE_VALUE,
 COMPARE_OPERATION,
 COMPUTE_OPERATION,
 GET_VALUE,
 POINT_VALUE) = range(5)

ARG_TYPE_LOOKUP = [
    'IMMEDIATE_VALUE',
    'COMPARE_OPERATION',
    'COMPUTE_OPERATION',
    'GET_VALUE',
    'POINT_VALUE'
]
