(IMMEDIATE_VALUE,
 COMPARE_OPERATION,
 COMPUTE_OPERATION,
 GET_VALUE_1,
 GET_POS_FROM_SCRIPT) = range(5)

ARG_TYPE_LOOKUP = [
    'IMMEDIATE_VALUE',
    'COMPARE_OPERATION',
    'COMPUTE_OPERATION',
    'GET_VALUE_1',
    'GET_POS_FROM_SCRIPT'
]
